services:
  scrapper-presenca-sessoes:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /apps/despesas-de-gabinete-e-presencas-de-sessoes/blumenau/presencas:/data/attendences:ro
    networks:
      - server_default

networks:
  server_default:
    external: true
